name: tuiter
description: Twitter based app to use Firebase Authentication, Firestore and Cloud Messaging

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_ui_auth: ^1.0.6
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true